### model
# DeepSeek R1 Distill Qwen 7B base 模型本地缓存路径
model_name_or_path: /root/.cache/modelscope/hub/models/deepseek-ai/DeepSeek-R1-Distill-Qwen-7B
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: lora
lora_rank: 16
lora_alpha: 32
lora_dropout: 0.05
lora_target: q_proj,k_proj,v_proj,o_proj
# 使用当前目录的 ZeRO-3 配置
deepspeed: /root/students/hebingyi/llama_factory_scripts/deepseek-qwen-7b/deepspeed_stage3_4gpu.json

### dataset
dataset_dir: /root/students/hebingyi/data/deepseek-qwen-7b
dataset: security_analysis
template: alpaca
cutoff_len: 1536
overwrite_cache: true
preprocessing_num_workers: 8
dataloader_num_workers: 2

### output
output_dir: /root/students/hebingyi/llama_factory_scripts/deepseek-qwen-7b/outputs/deepseek_qwen7b_lora
logging_steps: 10
save_strategy: steps
save_steps: 10
save_total_limit: 10
plot_loss: true
overwrite_output_dir: true
report_to: tensorboard
logging_dir: /root/students/hebingyi/llama_factory_scripts/deepseek-qwen-7b/tensorboard

### train
per_device_train_batch_size: 1
# 降低累计步以增加优化步数
gradient_accumulation_steps: 4
learning_rate: 1.0e-4
num_train_epochs: 40.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
gradient_checkpointing: true
flash_attn: auto
optim: adamw_torch
max_grad_norm: 1.0
packing: false
quantization_method: disabled

### eval
eval_strategy: "no"

### seed
seed: 42
